### ISSUE TITLE
g_pat returns slap instead of pat

### ISSUE THREAD

**Issue by flaunt5** [Godavaru/Godavaru#6]
https://github.com/Godavaru/Godavaru/blob/78af52ff5bade558bdee79aa7d181d512035be8d/cogs/action.py#L80

**Comment by stayberri** [comment]
Will be fixed in patch 1, which will be pushed later

Thanks for reporting btw

**Comment by stayberri** [comment]
This should be fixed now 👌

**Comment by flaunt5** [comment]
Awesome 😊
